apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80   #mandatory field
      nodePort: 30008 #if not specified automatically allocated in the ragne 30000-32827
  selector: #these are matched with the pod definition files having the below labels
    app: my-app
    type: front-end